[2024-06-17T13:28:53.137+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:28:53.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:28:53.323+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:28:53.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:28:53.444+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:28:53.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:28:53.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:28:53.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 1.016 seconds
[2024-06-17T13:29:25.046+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:29:25.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:29:25.216+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:29:25.205+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:29:25.642+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:29:25.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:29:25.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:29:26.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 1.653 seconds
[2024-06-17T13:29:57.587+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:29:57.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:29:57.664+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:29:57.657+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:29:57.771+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:29:57.742+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:29:57.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:29:58.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.796 seconds
[2024-06-17T13:30:29.616+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:30:29.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:30:29.658+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:30:29.649+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:30:29.888+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:30:29.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:30:29.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:30:30.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 1.177 seconds
[2024-06-17T13:31:01.163+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:31:01.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:31:01.166+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:31:01.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:31:01.184+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:31:01.180+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:31:01.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:31:01.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.377 seconds
[2024-06-17T13:31:32.093+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:31:32.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:31:32.096+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:31:32.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:31:32.113+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:31:32.109+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:31:32.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:31:32.212+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.125 seconds
[2024-06-17T13:32:02.521+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:32:02.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:32:02.526+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:32:02.525+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:32:02.550+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:32:02.544+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:32:02.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:32:02.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.161 seconds
[2024-06-17T13:32:33.157+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:32:33.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:32:33.160+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:32:33.160+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:32:33.179+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:32:33.175+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:32:33.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:32:33.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.143 seconds
[2024-06-17T13:33:03.518+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:33:03.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:33:03.520+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:33:03.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:33:03.541+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:33:03.536+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:33:03.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:33:03.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.136 seconds
[2024-06-17T13:33:34.125+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:33:34.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:33:34.128+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:33:34.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:33:34.147+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:33:34.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:33:34.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:33:34.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.122 seconds
[2024-06-17T13:34:04.699+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:34:04.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:34:04.701+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:34:04.701+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:34:04.721+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:34:04.715+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:34:04.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:34:04.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.125 seconds
[2024-06-17T13:34:35.268+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:34:35.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:34:35.270+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:34:35.270+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:34:35.287+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:34:35.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:34:35.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:34:35.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.117 seconds
[2024-06-17T13:35:05.751+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/historical_dag.py
[2024-06-17T13:35:05.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/historical_dag.py for tasks to queue
[2024-06-17T13:35:05.755+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:35:05.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:35:05.783+0000] {logging_mixin.py:188} INFO - [2024-06-17T13:35:05.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/historical_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/historical_dag.py", line 5, in <module>
    from scripts.historical_functions import get_and_preproc_historical_data, send_to_postgresql_historical_data
ModuleNotFoundError: No module named 'scripts.historical_functions'
[2024-06-17T13:35:05.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/historical_dag.py
[2024-06-17T13:35:05.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/historical_dag.py took 0.215 seconds
